// examples/nextjs-demo/src/components/InstallGuide.tsx
import React from 'react';

const InstallGuide = () => {
  return (
    <div className="mt-10 max-w-3xl">
      <h2 className="text-2xl font-bold mb-6">Installation Steps</h2>
      
      <div className="mb-6">
        <h3 className="text-xl font-semibold mb-2">1. Install Dependencies</h3>
        <pre className="bg-gray-100 p-4 rounded-md">
          {`npm install bytedesk-web\n# or\nyarn add bytedesk-web`}
        </pre>
      </div>

      <div className="mb-6">
        <h3 className="text-xl font-semibold mb-2">2. Import Component</h3>
        <pre className="bg-gray-100 p-4 rounded-md">
          {`'use client';\n\nimport { BytedeskNextjs } from 'bytedesk-web/nextjs';\nimport type { BytedeskConfig } from 'bytedesk-web/nextjs';`}
        </pre>
      </div>

      <div className="mb-6">
        <h3 className="text-xl font-semibold mb-2">3. Configure Parameters</h3>
        <pre className="bg-gray-100 p-4 rounded-md">
          {`const config: BytedeskConfig = {
  placement: 'bottom-right',
  marginBottom: 20,
  marginSide: 20,
  bubbleConfig: {
    show: true,
    icon: '👋',
    title: 'Need help?',
    subtitle: 'Click to chat'
  },
  chatConfig: {
    org: 'df_org_uid',  // Replace with your organization ID
    t: "2",
    sid: 'df_rt_uid'    // Replace with your session ID
  }
};`}
        </pre>
      </div>

      <div className="mb-6">
        <h3 className="text-xl font-semibold mb-2">4. Use Component</h3>
        <pre className="bg-gray-100 p-4 rounded-md">
          {`export default function Page() {
  return (
    <div>
      <BytedeskNextjs config={config} />
      <button onClick={() => (window as any).bytedesk?.showChat()}>
        Open Chat
      </button>
    </div>
  );
}`}
        </pre>
      </div>

      <div>
        <h3 className="text-xl font-semibold mb-2">5. Available Methods</h3>
        <ul className="list-disc pl-5 space-y-2">
          <li><code className="bg-gray-100 px-2 py-1 rounded">(window as any).bytedesk?.showChat()</code> - Show chat window</li>
          <li><code className="bg-gray-100 px-2 py-1 rounded">(window as any).bytedesk?.hideChat()</code> - Hide chat window</li>
        </ul>
      </div>
    </div>
  );
};

export default InstallGuide;

// examples/angular-demo/src/components/install-guide.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-install-guide',
  template: `
    <div style="margin-top: 40px; max-width: 800px">
      <h2>Installation Steps</h2>
      
      <div style="margin-bottom: 20px">
        <h3>1. Install Dependencies</h3>
        <pre style="background: #f5f5f5; padding: 15px; border-radius: 4px">
npm install bytedesk-web
# or
yarn add bytedesk-web</pre>
      </div>

      <div style="margin-bottom: 20px">
        <h3>2. Import Component</h3>
        <pre style="background: #f5f5f5; padding: 15px; border-radius: 4px">
import &#123; BytedeskAngular &#125; from 'bytedesk-web/angular';
import type &#123; BytedeskConfig &#125; from 'bytedesk-web/angular';</pre>
      </div>

      <div style="margin-bottom: 20px">
        <h3>3. Configure Parameters</h3>
        <pre style="background: #f5f5f5; padding: 15px; border-radius: 4px">
const config: BytedeskConfig = &#123;
  htmlUrl: 'https://ai.bytedesk.com',
  placement: 'bottom-right',
  marginBottom: 20,
  marginSide: 20,
  chatConfig: &#123;
    org: 'your_org_id',  // Replace with your organization ID
    t: "2",
    sid: 'your_sid'      // Replace with your SID
  &#125;
&#125;;</pre>
      </div>

      <div style="margin-bottom: 20px">
        <h3>4. Use Component</h3>
        <pre style="background: #f5f5f5; padding: 15px; border-radius: 4px">
@Component(&#123;
  template: \`
    &lt;bytedesk-angular [config]="config"&gt;&lt;/bytedesk-angular&gt;
    &lt;button (click)="showChat()"&gt;Open Chat&lt;/button&gt;
  \`
&#125;)
export class AppComponent &#123;
  config = &#123;
    // ... configuration
  &#125;;

  showChat() &#123;
    (window as any).bytedesk?.showChat();
  &#125;
&#125;</pre>
      </div>

      <div>
        <h3>5. Available Methods</h3>
        <ul style="line-height: 1.6">
          <li><code>(window as any).bytedesk?.showChat()</code> - Show chat window</li>
          <li><code>(window as any).bytedesk?.hideChat()</code> - Hide chat window</li>
        </ul>
      </div>
    </div>
  `
})
export class InstallGuide {}
