// examples/react-demo/src/pages/CallCenterDemo.tsx
import { useMemo } from 'react';
import { Alert, Button, Card, List, Space, Tag, Typography, theme as antdTheme } from 'antd';
// @ts-ignore
import { BytedeskReact } from '@bytedesk/web/adapters/react';
// @ts-ignore
import type { BytedeskConfig, Language, Theme as BytedeskTheme } from '@bytedesk/web/types';
import { getLocaleMessages } from '../locales';
import CurrentUserProfile from '../components/CurrentUserProfile';
import PageContainer from '../components/PageContainer';
import { DEMO_USER_PRESETS, type DemoUserKey, type DemoUserProfile } from '../types/demo-user';
import { formatChatConfigQuery, getConsultButtonLabel, type DemoChatProfile } from '../types/chat-profile';

interface DemoPageProps {
  locale: Language;
  themeMode: BytedeskTheme['mode'];
  selectedChatProfile: DemoChatProfile;
  selectedUser: DemoUserProfile;
  isAnonymousMode: boolean;
  onSelectUser: (nextUser: DemoUserKey) => void;
  onAnonymousModeChange: (nextMode: boolean) => void;
}

const CallCenterDemo = ({ locale, themeMode, selectedChatProfile, selectedUser, isAnonymousMode, onSelectUser, onAnonymousModeChange }: DemoPageProps) => {
  const messages = useMemo(() => getLocaleMessages(locale), [locale]);
  const { token } = antdTheme.useToken();

  const users = useMemo(
    () => (Object.keys(DEMO_USER_PRESETS) as DemoUserKey[]).map((key) => ({
      key,
      visitorUid: DEMO_USER_PRESETS[key].visitorUid,
      avatar: DEMO_USER_PRESETS[key].avatar,
      nickname: messages.pages.userInfoDemo.users[key]
    })),
    [messages]
  );

  const config = useMemo<BytedeskConfig>(() => ({
    isDebug: true,
    htmlUrl: process.env.NODE_ENV === 'development'
      ? 'http://127.0.0.1:9022/call'
      : 'https://cdn.weiyuai.cn/call',
    ...(process.env.NODE_ENV === 'development' ? { apiUrl: 'http://127.0.0.1:9003' } : {}),
    chatPath: '/chat',
    placement: 'bottom-right',
    marginBottom: 20,
    marginSide: 20,
    autoPopup: false,
    draggable: true,
    bubbleConfig: {
      show: true,
      icon: '📞',
      title: messages.pages.callCenterDemo.bubbleTitle,
      subtitle: messages.pages.callCenterDemo.bubbleSubtitle
    },
    buttonConfig: {
      show: true,
      width: 60,
      height: 60
    },
    chatConfig: {
      ...selectedChatProfile.chatConfig,
      ...(isAnonymousMode
        ? {}
        : {
          visitorUid: selectedUser.visitorUid,
          nickname: selectedUser.nickname,
          avatar: selectedUser.avatar
        })
    },
    theme: {
      mode: themeMode
    },
    locale
  }), [isAnonymousMode, locale, messages, selectedChatProfile, selectedUser, themeMode]);

  const docLinks = useMemo(
    () => [
      { href: 'https://www.weiyuai.cn/docs/zh-CN/docs/channel/react', label: messages.pages.callCenterDemo.docLinks.reactDoc },
      { href: 'https://www.weiyuai.cn/docs/zh-CN/docs/channel/vue', label: messages.pages.callCenterDemo.docLinks.vueDoc },
      { href: 'https://github.com/Bytedesk/bytedesk-web/blob/master/examples/react-demo/src/pages/CallCenterDemo.tsx', label: messages.pages.callCenterDemo.docLinks.reactExample }
    ],
    [messages]
  );

  const sampleUrl = useMemo(() => {
    const baseHtmlUrl = process.env.NODE_ENV === 'development'
      ? 'http://127.0.0.1:9022/call'
      : 'https://cdn.weiyuai.cn/call';
    const params = new URLSearchParams();
    const appendIfPresent = (key: string, value: string | undefined) => {
      if (value) {
        params.append(key, value);
      }
    };
    params.append('org', selectedChatProfile.chatConfig.org);
    params.append('t', String(selectedChatProfile.chatConfig.t));
    params.append('sid', String(selectedChatProfile.chatConfig.sid));
    if (!isAnonymousMode) {
      appendIfPresent('visitorUid', selectedUser.visitorUid);
      appendIfPresent('nickname', selectedUser.nickname);
      appendIfPresent('avatar', selectedUser.avatar);
    }
    params.append('lang', locale);
    params.append('mode', String(themeMode || 'light'));
    return `${baseHtmlUrl}?${params.toString()}`;
  }, [isAnonymousMode, locale, selectedChatProfile, selectedUser, themeMode]);
  const chatConfigHint = formatChatConfigQuery(selectedChatProfile.chatConfig);
  const consultButtonLabel = useMemo(() => {
    const defaultLabel = getConsultButtonLabel(selectedChatProfile, locale);
    return locale === 'zh-cn' ? defaultLabel.replace(/^咨询/, '呼叫') : defaultLabel;
  }, [locale, selectedChatProfile]);

  const formatSwitchUserLabel = (name: string) =>
    messages.pages.userInfoDemo.switchToUserLabel.replace('{{name}}', name);

  return (
    <PageContainer>
      <Card>
        <Space direction="vertical" size="middle" style={{ width: '100%' }}>
          <Typography.Title level={2} style={{ marginBottom: 0 }}>
            {messages.pages.callCenterDemo.title}
          </Typography.Title>
          <Typography.Paragraph type="secondary" style={{ marginBottom: 0 }}>
            {messages.pages.callCenterDemo.description}
          </Typography.Paragraph>
          <Space direction="vertical" size={4}>
            {docLinks.map((link) => (
              <Typography.Link key={link.href} href={link.href} target="_blank" rel="noopener noreferrer">
                {link.label}
              </Typography.Link>
            ))}
          </Space>
          <Alert
            type="info"
            showIcon
            message={messages.pages.callCenterDemo.pathAlert}
          />
        </Space>
      </Card>

      <Card>
        <Space direction="vertical" size="middle" style={{ width: '100%' }}>
          <Space align="center" wrap>
            <Typography.Text strong>{messages.pages.callCenterDemo.currentPathLabel}</Typography.Text>
            <Tag color="processing">/call</Tag>
            <Typography.Text type="secondary">{messages.pages.callCenterDemo.currentPathHint}</Typography.Text>
          </Space>

          <Space direction="vertical" size={8} style={{ width: '100%' }}>
            <CurrentUserProfile
              title={messages.pages.userInfoDemo.currentUserTitle}
              isAnonymousMode={isAnonymousMode}
              avatar={selectedUser.avatar}
              anonymousIdText={messages.pages.callCenterDemo.anonymousUserHint}
              anonymousNicknameText={messages.pages.userInfoDemo.anonymousUserLabel}
              userIdLabel={messages.pages.userInfoDemo.currentUserIdLabel}
              userId={selectedUser.visitorUid}
              userNicknameLabel={messages.pages.userInfoDemo.currentUserNicknameLabel}
              userNickname={selectedUser.nickname}
              compact
            />
            <Space wrap>
              {users.map((user) => (
                <Button
                  key={user.visitorUid}
                  type="primary"
                  onClick={() => {
                    if (!isAnonymousMode && selectedUser.key === user.key) {
                      return;
                    }
                    onAnonymousModeChange(false);
                    onSelectUser(user.key);
                  }}
                  style={!isAnonymousMode && selectedUser.key === user.key ? { backgroundColor: token.colorSuccess, borderColor: token.colorSuccess } : undefined}
                >
                  {formatSwitchUserLabel(user.nickname)}
                  {!isAnonymousMode && selectedUser.key === user.key ? '【当前】' : ''}
                </Button>
              ))}
              <Button
                type={isAnonymousMode ? 'primary' : 'default'}
                onClick={() => {
                  if (isAnonymousMode) {
                    return;
                  }
                  onAnonymousModeChange(true);
                }}
                style={isAnonymousMode ? { backgroundColor: token.colorSuccess, borderColor: token.colorSuccess } : undefined}
              >
                {messages.pages.callCenterDemo.buttons.switchAnonymousUser}
                {isAnonymousMode ? '【当前】' : ''}
              </Button>
            </Space>
          </Space>

          <Space wrap>
            <Button type="primary" onClick={() => (window as any).bytedesk?.showChat()}>
              {consultButtonLabel}
            </Button>
            <Button onClick={() => (window as any).bytedesk?.hideChat()}>{messages.common.buttons.closeChat}</Button>
            <Button onClick={() => window.open(sampleUrl, '_blank', 'width=420,height=680,resizable=yes,scrollbars=yes')}>
              {messages.common.buttons.openInNewWindow}
            </Button>
            <Button onClick={() => window.open(sampleUrl, '_blank')}>
              {messages.common.buttons.openInNewTab}
            </Button>
          </Space>

          <Alert
            type="info"
            showIcon
            message={`${messages.common.apiHintPrefix} showChat() / hideChat()`}
            style={{ alignSelf: 'flex-start', width: 'fit-content', maxWidth: '100%' }}
          />
          <Alert
            type="info"
            showIcon
            message={`咨询参数: ${chatConfigHint}`}
            style={{ alignSelf: 'flex-start', width: 'fit-content', maxWidth: '100%' }}
          />

          <List
            header={messages.pages.callCenterDemo.usageTitle}
            dataSource={messages.pages.callCenterDemo.usageNotes}
            renderItem={(note) => <List.Item>{note}</List.Item>}
          />
        </Space>
      </Card>

      <Card title={messages.pages.callCenterDemo.urlGuideTitle}>
        <Space direction="vertical" size="middle" style={{ width: '100%' }}>
          <Typography.Text strong>{messages.pages.callCenterDemo.sampleUrlLabel}</Typography.Text>
          <Typography.Paragraph copyable={{ text: sampleUrl }} style={{ marginBottom: 0 }}>
            <pre style={{ margin: 0, whiteSpace: 'pre-wrap', wordBreak: 'break-all' }}>{sampleUrl}</pre>
          </Typography.Paragraph>
        </Space>
      </Card>

      <BytedeskReact {...config} />
    </PageContainer>
  );
};

export default CallCenterDemo;

// examples/vue-demo/src/pages/CallCenterDemo.vue
<!--
 * @Description: Call Center Demo for Vue
-->
<template>
  <PageContainer>
    <div class="card">
      <h2>呼叫中心演示</h2>
      <p class="desc">演示呼叫中心音频通话功能，使用 /call 路径</p>
    </div>

    <div class="card">
      <div class="controls">
        <label class="radio-label">
          <input type="radio" v-model="audioPreset" value="echo" /> Echo测试
        </label>
        <label class="radio-label">
          <input type="radio" v-model="audioPreset" value="ai" /> AI音频
        </label>
        <label class="radio-label">
          <input type="radio" v-model="audioPreset" value="ivr" /> IVR
        </label>
      </div>
      <div class="controls" style="margin-top: 12px">
        <button class="btn primary" @click="showCallEmbed">嵌入方式打开</button>
        <button class="btn" @click="showCallPopup">弹窗方式打开</button>
        <button class="btn" @click="showCallNewTab">新标签页打开</button>
      </div>
    </div>

    <div class="card">
      <h3>URL 参数</h3>
      <table class="route-table">
        <thead><tr><th>参数</th><th>值</th><th>说明</th></tr></thead>
        <tbody>
          <tr v-for="row in urlParamRows" :key="row.param">
            <td><code>{{ row.param }}</code></td>
            <td><code>{{ row.value }}</code></td>
            <td>{{ row.note }}</td>
          </tr>
        </tbody>
      </table>
    </div>

    <BytedeskVue v-bind="config" />
  </PageContainer>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue';
// @ts-ignore
import { BytedeskVue } from '@bytedesk/web/adapters/vue';
// @ts-ignore
import type { BytedeskConfig, Language } from '@bytedesk/web/types';
import { getLocaleMessages } from '../locales';
import PageContainer from '../components/PageContainer.vue';
import type { DemoUserProfile } from '../types/demo-user';
import type { DemoChatProfile } from '../types/chat-profile';
import { demoApiUrl, getDemoHtmlBaseUrl } from '../utils/env';
import { buildUrlParamRowsWithEncodeHint } from '../utils/url-param-guide';

interface Props {
  locale: Language;
  themeMode: string;
  selectedChatProfile: DemoChatProfile;
  selectedUser: DemoUserProfile;
  isAnonymousMode: boolean;
}

const props = defineProps<Props>();
const audioPreset = ref<'echo' | 'ai' | 'ivr'>('echo');

const messages = computed(() => getLocaleMessages(props.locale));
const htmlBaseUrl = getDemoHtmlBaseUrl(9006);

const urlParamRows = computed(() => buildUrlParamRowsWithEncodeHint(
  `org=${props.selectedChatProfile.chatConfig.org}&t=${props.selectedChatProfile.chatConfig.t}&sid=${props.selectedChatProfile.chatConfig.sid}&audioPreset=${audioPreset.value}`,
  props.locale
));

const config = computed<BytedeskConfig>(() => ({
  isDebug: true,
  htmlUrl: htmlBaseUrl,
  ...(demoApiUrl ? { apiUrl: demoApiUrl } : {}),
  chatPath: '/call',
  placement: 'bottom-right',
  marginBottom: 20,
  marginSide: 20,
  autoPopup: false,
  draggable: true,
  bubbleConfig: { show: true, icon: '📞', title: '呼叫中心', subtitle: '点击开始通话' },
  buttonConfig: { show: true, action: 'chat' },
  chatConfig: {
    ...props.selectedChatProfile.chatConfig,
    audioPreset: audioPreset.value,
    ...(props.isAnonymousMode ? {} : {
      visitorUid: props.selectedUser.visitorUid,
      nickname: props.selectedUser.nickname,
      avatar: props.selectedUser.avatar,
    }),
  },
  theme: { mode: props.themeMode as any },
  locale: props.locale,
}));

function showCallEmbed() {
  (window as any).bytedesk?.showChat();
}

function showCallPopup() {
  const params = new URLSearchParams();
  params.append('org', props.selectedChatProfile.chatConfig.org);
  params.append('t', props.selectedChatProfile.chatConfig.t);
  params.append('sid', props.selectedChatProfile.chatConfig.sid);
  params.append('audioPreset', audioPreset.value);
  window.open(`${htmlBaseUrl}/call?${params.toString()}`, '_blank', 'width=420,height=680');
}

function showCallNewTab() {
  const params = new URLSearchParams();
  params.append('org', props.selectedChatProfile.chatConfig.org);
  params.append('t', props.selectedChatProfile.chatConfig.t);
  params.append('sid', props.selectedChatProfile.chatConfig.sid);
  params.append('audioPreset', audioPreset.value);
  window.open(`${htmlBaseUrl}/call?${params.toString()}`, '_blank');
}
</script>

<style scoped>
.card { background: #fff; border-radius: 8px; padding: 24px; margin-bottom: 16px; }
.desc { color: #666; margin-top: 8px; }
.route-table { width: 100%; border-collapse: collapse; margin-top: 12px; }
.route-table th, .route-table td { border: 1px solid #e8e8e8; padding: 8px 12px; text-align: left; font-size: 13px; }
.route-table th { background: #fafafa; }
.btn { padding: 6px 16px; border: 1px solid #d9d9d9; border-radius: 6px; background: #fff; cursor: pointer; font-size: 13px; }
.btn.primary { background: #1677ff; color: #fff; border-color: #1677ff; }
.controls { display: flex; gap: 12px; align-items: center; flex-wrap: wrap; }
.radio-label { font-size: 13px; display: flex; align-items: center; gap: 4px; cursor: pointer; }
code { background: #f6f8fa; padding: 1px 6px; border-radius: 3px; font-size: 12px; }
</style>
