// examples/vue-demo/src/pages/ThreadHistoryDemo.vue
<!--
 * @Description: Thread History Demo for Vue
-->
<template>
  <PageContainer>
    <div class="card">
      <h2>{{ messages.pages.threadHistoryDemo.title }}</h2>
      <p class="desc">{{ messages.pages.threadHistoryDemo.description }}</p>
    </div>

    <div class="card">
      <div class="controls">
        <label class="checkbox-label">
          <input type="checkbox" v-model="threadDetailEnabled" />
          threadDetail 参数: {{ threadDetailEnabled ? '1 (显示详情)' : '0 (隐藏详情)' }}
        </label>
      </div>
      <div class="controls" style="margin-top: 12px">
        <button class="btn primary" @click="showThreadHistory">打开历史会话</button>
      </div>
    </div>

    <div class="card">
      <h3>URL 参数</h3>
      <table class="route-table">
        <thead><tr><th>参数</th><th>值</th><th>说明</th></tr></thead>
        <tbody>
          <tr v-for="row in urlParamRows" :key="row.param">
            <td><code>{{ row.param }}</code></td>
            <td><code>{{ row.value }}</code></td>
            <td>{{ row.note }}</td>
          </tr>
        </tbody>
      </table>
    </div>

    <BytedeskVue v-bind="config" />
  </PageContainer>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue';
// @ts-ignore
import { BytedeskVue } from '@bytedesk/web/adapters/vue';
// @ts-ignore
import type { BytedeskConfig, Language } from '@bytedesk/web/types';
import { getLocaleMessages } from '../locales';
import PageContainer from '../components/PageContainer.vue';
import type { DemoUserKey, DemoUserProfile } from '../types/demo-user';
import type { DemoChatProfile } from '../types/chat-profile';
import { demoApiUrl, getDemoHtmlBaseUrl } from '../utils/env';
import { buildUrlParamRowsWithEncodeHint } from '../utils/url-param-guide';

interface Props {
  locale: Language;
  themeMode: string;
  selectedChatProfile: DemoChatProfile;
  selectedUser: DemoUserProfile;
  isAnonymousMode: boolean;
}

const props = defineProps<Props>();
const threadDetailEnabled = ref(false);

const messages = computed(() => getLocaleMessages(props.locale));
const htmlBaseUrl = getDemoHtmlBaseUrl(9006);

const urlParamRows = computed(() => {
  const params = new URLSearchParams();
  params.append('org', props.selectedChatProfile.chatConfig.org);
  params.append('t', props.selectedChatProfile.chatConfig.t);
  params.append('sid', props.selectedChatProfile.chatConfig.sid);
  params.append('threadDetail', threadDetailEnabled.value ? '1' : '0');
  if (!props.isAnonymousMode) {
    params.append('visitorUid', props.selectedUser.visitorUid);
    params.append('nickname', encodeURIComponent(props.selectedUser.nickname));
    params.append('avatar', encodeURIComponent(props.selectedUser.avatar));
  }
  return buildUrlParamRowsWithEncodeHint(params.toString(), props.locale);
});

const config = computed<BytedeskConfig>(() => ({
  isDebug: true,
  htmlUrl: htmlBaseUrl,
  ...(demoApiUrl ? { apiUrl: demoApiUrl } : {}),
  placement: 'bottom-right',
  marginBottom: 20,
  marginSide: 20,
  autoPopup: false,
  draggable: true,
  bubbleConfig: { show: true, icon: '🧵', title: '历史会话', subtitle: '点击查看历史' },
  buttonConfig: { show: true, width: 60, height: 60, action: 'thread' },
  chatConfig: {
    ...props.selectedChatProfile.chatConfig,
    threadDetail: threadDetailEnabled.value ? '1' : '0',
    ...(props.isAnonymousMode ? {} : {
      visitorUid: props.selectedUser.visitorUid,
      nickname: props.selectedUser.nickname,
      avatar: props.selectedUser.avatar,
    }),
  },
  theme: { mode: props.themeMode as any },
  locale: props.locale,
}));

function showThreadHistory() {
  (window as any).bytedesk?.showChat();
}
</script>

<style scoped>
.card { background: #fff; border-radius: 8px; padding: 24px; margin-bottom: 16px; }
.desc { color: #666; margin-top: 8px; }
.route-table { width: 100%; border-collapse: collapse; margin-top: 12px; }
.route-table th, .route-table td { border: 1px solid #e8e8e8; padding: 8px 12px; text-align: left; font-size: 13px; }
.route-table th { background: #fafafa; }
.btn { padding: 6px 16px; border: 1px solid #d9d9d9; border-radius: 6px; background: #fff; cursor: pointer; font-size: 13px; }
.btn.primary { background: #1677ff; color: #fff; border-color: #1677ff; }
.controls { display: flex; gap: 12px; align-items: center; flex-wrap: wrap; }
.checkbox-label { font-size: 13px; display: flex; align-items: center; gap: 4px; cursor: pointer; }
code { background: #f6f8fa; padding: 1px 6px; border-radius: 3px; font-size: 12px; }
</style>

// examples/react-demo/src/pages/ThreadHistoryDemo.tsx
import { useMemo, useState } from 'react';
import { Alert, Button, Card, Divider, FloatButton, Space, Table, Tag, Typography, theme as antdTheme } from 'antd';
// @ts-ignore
import { BytedeskReact } from '@bytedesk/web/adapters/react';
// @ts-ignore
import type { BytedeskConfig, Language, Theme as BytedeskTheme } from '@bytedesk/web/types';
import { getLocaleMessages } from '../locales';
import PageContainer from '../components/PageContainer';
import type { DemoUserKey, DemoUserProfile } from '../types/demo-user';
import type { DemoChatProfile } from '../types/chat-profile';
import { demoApiUrl, getDemoHtmlBaseUrl } from '../utils/env';
import { buildUrlParamRowsWithEncodeHint } from '../utils/url-param-guide';
import { buildCurrentEmbedCodeExample, getCurrentEmbedCodeCopy } from '../utils/embed-code-guide';

interface DemoPageProps {
  locale: Language;
  themeMode: BytedeskTheme['mode'];
  selectedChatProfile: DemoChatProfile;
  selectedUser: DemoUserProfile;
  isAnonymousMode: boolean;
  onSelectUser: (nextUser: DemoUserKey) => void;
  onAnonymousModeChange: (nextMode: boolean) => void;
}

const ThreadHistoryDemo = ({ locale, themeMode, selectedChatProfile, selectedUser, isAnonymousMode }: DemoPageProps) => {
  const messages = useMemo(() => getLocaleMessages(locale), [locale]);
  const { token } = antdTheme.useToken();
  const htmlBaseUrl = getDemoHtmlBaseUrl(9006);
  const [isThreadDetailParamEnabled, setIsThreadDetailParamEnabled] = useState<boolean>(false);
  const config = useMemo<BytedeskConfig>(() => ({
    isDebug: true,
    htmlUrl: htmlBaseUrl,
    ...(demoApiUrl ? { apiUrl: demoApiUrl } : {}),
    placement: 'bottom-right',
    marginBottom: 20,
    marginSide: 20,
    autoPopup: false,
    draggable: true,
    bubbleConfig: {
      show: true,
      icon: '🧵',
      title: messages.pages.threadHistoryDemo.bubbleTitle,
      subtitle: messages.pages.threadHistoryDemo.bubbleSubtitle
    },
    buttonConfig: {
      show: true,
      width: 60,
      height: 60,
      action: 'thread'
    },
    chatConfig: {
      ...selectedChatProfile.chatConfig,
      threadDetail: isThreadDetailParamEnabled ? '1' : '0',
      ...(isAnonymousMode
        ? {}
        : {
          visitorUid: selectedUser.visitorUid,
          nickname: selectedUser.nickname,
          avatar: selectedUser.avatar
        })
    },
    theme: {
      mode: themeMode
    },
    locale
  }), [htmlBaseUrl, isAnonymousMode, isThreadDetailParamEnabled, locale, messages, selectedChatProfile, selectedUser, themeMode]);

  const docLinks = useMemo(
    () => [
      { href: 'https://www.weiyuai.cn/docs/zh-CN/docs/development/thread_history', label: messages.pages.threadHistoryDemo.docLinks.threadDoc },
      { href: 'https://github.com/Bytedesk/bytedesk-web/blob/master/examples/react-demo/src/pages/ThreadHistoryDemo.tsx', label: messages.pages.threadHistoryDemo.docLinks.reactExample }
    ],
    [messages]
  );

  const demoVisitorUid = useMemo(
    () => (isAnonymousMode ? 'visitor_001' : (selectedUser.visitorUid || 'visitor_001')),
    [isAnonymousMode, selectedUser.visitorUid]
  );

  // const urlTemplate = useMemo(() => {
  //   return '{{BASE_URL}}/chat/thread?visitorUid=visitor_001&lang=zh-cn&mode=light';
  // }, []);

  const sampleUrl = useMemo(() => {
    const params = new URLSearchParams();
    params.append('visitorUid', demoVisitorUid);
    params.append('lang', locale);
    params.append('mode', String(themeMode || 'light'));
    if (isThreadDetailParamEnabled) {
      params.append('threadDetail', '1');
    }
    return `${htmlBaseUrl}/chat/thread?${params.toString()}`;
  }, [demoVisitorUid, htmlBaseUrl, isThreadDetailParamEnabled, locale, themeMode]);

  const usageNotes = messages.pages.threadHistoryDemo.usageNotes;
  const urlParams = messages.pages.threadHistoryDemo.urlParams;
  const requiredUrlParams = useMemo(() => new Set(['visitorUid']), []);
  const embedCodeCopy = useMemo(() => getCurrentEmbedCodeCopy(locale), [locale]);
  const codeBlockStyle = useMemo(() => ({
    margin: 0,
    padding: '12px 14px',
    borderRadius: 8,
    border: `1px solid ${token.colorBorderSecondary || token.colorBorder}`,
    background: token.colorFillQuaternary,
    fontSize: 12,
    lineHeight: 1.7,
    fontFamily: 'SFMono-Regular, Consolas, Liberation Mono, Menlo, monospace',
    whiteSpace: 'pre-wrap' as const,
    wordBreak: 'break-all' as const
  }), [token.colorBorder, token.colorBorderSecondary, token.colorFillQuaternary]);
  const threadHistoryMessages = messages.pages.threadHistoryDemo;
  const threadApiGuide = useMemo(() => {
    const endpoint = '/visitor/api/v1/threads';
    const apiHost = (config.apiUrl || 'https://{YOUR_API_HOST}').replace(/\/+$/, '');
    const queryParams = threadHistoryMessages.apiGuide.queryParams;
    const pagingMapping = threadHistoryMessages.apiGuide.pagingMapping;
    const fullUrlPage1 = `${apiHost}${endpoint}?visitorUid=${encodeURIComponent(demoVisitorUid)}&pageNumber=0&pageSize=10&searchText=`;
    const fullUrlPage2 = `${apiHost}${endpoint}?visitorUid=${encodeURIComponent(demoVisitorUid)}&pageNumber=1&pageSize=10&searchText=`;
    const curlExample = `curl --request GET \\
  --url '${fullUrlPage1}'`;
    const fetchExample = `const params = new URLSearchParams({\n  visitorUid: '${demoVisitorUid}',\n  pageNumber: '0',\n  pageSize: '10',\n  searchText: ''\n});\n\nconst resp = await fetch(\`${apiHost}${endpoint}?\${params.toString()}\`, {\n  method: 'GET',\n  credentials: 'include'\n});\nconst data = await resp.json();`;
    const anonymousHint = threadHistoryMessages.apiGuide.anonymousHint;

    return { endpoint, queryParams, pagingMapping, fullUrlPage1, fullUrlPage2, curlExample, fetchExample, anonymousHint };
  }, [config.apiUrl, demoVisitorUid, threadHistoryMessages.apiGuide.anonymousHint, threadHistoryMessages.apiGuide.pagingMapping, threadHistoryMessages.apiGuide.queryParams]);
  const currentUrlParamMap = useMemo(() => new URL(sampleUrl).searchParams, [sampleUrl]);
  const urlParamRows = useMemo(
    () => buildUrlParamRowsWithEncodeHint(urlParams, currentUrlParamMap, locale, ['visitorUid']),
    [currentUrlParamMap, locale, urlParams]
  );
  const currentEmbedCodeExample = useMemo(
    () => buildCurrentEmbedCodeExample({ config }),
    [config]
  );

  const responseTopLevelFields = threadHistoryMessages.responseGuide.topLevelFields;
  const responseDataFields = threadHistoryMessages.responseGuide.dataFields;
  const threadItemFields = threadHistoryMessages.responseGuide.threadItemFields;

  return (
    <PageContainer>
      <Card>
        <Space orientation="vertical" size="middle" style={{ width: '100%' }}>
          <Typography.Title level={2} style={{ marginBottom: 0 }}>
            {messages.pages.threadHistoryDemo.title}
          </Typography.Title>
          <Typography.Paragraph type="secondary" style={{ marginBottom: 0 }}>
            {messages.pages.threadHistoryDemo.description}
          </Typography.Paragraph>
          <Space orientation="vertical" size={4}>
            {docLinks.map((link) => (
              <Typography.Link key={link.href} href={link.href} target="_blank" rel="noopener noreferrer">
                {link.label}
              </Typography.Link>
            ))}
          </Space>
        </Space>
      </Card>

      <Card>
        <Space orientation="vertical" size="middle" style={{ width: '100%' }}>
          <Space align="center" wrap>
            <Typography.Text strong>{messages.pages.threadHistoryDemo.currentPathLabel}</Typography.Text>
            <Tag color="processing">/chat/thread</Tag>
            <Typography.Text type="secondary">{messages.pages.threadHistoryDemo.currentPathHint}</Typography.Text>
          </Space>

          <Space orientation="vertical" size={8} style={{ width: '100%' }}>
            <Space wrap>
              <Button type={isThreadDetailParamEnabled ? 'primary' : 'default'} onClick={() => setIsThreadDetailParamEnabled((prev) => !prev)}>
              {messages.pages.basicDemo.threadDetailParamLabel}: {isThreadDetailParamEnabled ? messages.pages.basicDemo.loadHistoryEnabled : messages.pages.basicDemo.loadHistoryDisabled}
            </Button>
            </Space>

            <Divider style={{ margin: '4px 0' }} />

            <Space wrap>
              <Button type="primary" onClick={() => (window as any).bytedesk?.showThread()}>
                {threadHistoryMessages.buttons.openHistoryPage}
              </Button>
            <Button onClick={() => (window as any).bytedesk?.hideChat()}>{messages.common.buttons.closeChat}</Button>
            <Button onClick={() => window.open(sampleUrl, '_blank', 'width=420,height=680,resizable=yes,scrollbars=yes')}>
              {messages.common.buttons.openInNewWindow}
            </Button>
            <Button onClick={() => window.open(sampleUrl, '_blank')}>
              {messages.common.buttons.openInNewTab}
            </Button>
            </Space>
          </Space>

          <Alert
            type="info"
            showIcon
            title={`${messages.common.apiHintPrefix} showThread() / hideChat()`}
            style={{ alignSelf: 'flex-start', width: 'fit-content', maxWidth: '100%' }}
          />

          <div>
            <Typography.Text strong>{messages.pages.threadHistoryDemo.usageTitle}</Typography.Text>
            <ul style={{ margin: '8px 0 0', paddingLeft: 20, lineHeight: 1.8 }}>
              {usageNotes.map((note) => (
                <li key={note}>{note}</li>
              ))}
            </ul>
          </div>
        </Space>
      </Card>

      <Card title={messages.pages.threadHistoryDemo.urlGuideTitle}>
        <Space orientation="vertical" size="middle" style={{ width: '100%' }}>
          {/* <Typography.Text strong>{messages.pages.threadHistoryDemo.urlTemplateLabel}</Typography.Text> */}
          {/* <pre style={{ margin: 0, whiteSpace: 'pre-wrap', wordBreak: 'break-all' }}>{urlTemplate}</pre> */}

          <Typography.Text strong>{messages.pages.threadHistoryDemo.sampleUrlLabel}</Typography.Text>
          <pre style={{ margin: 0, whiteSpace: 'pre-wrap', wordBreak: 'break-all' }}>{sampleUrl}</pre>

          <Typography.Text strong>{messages.pages.threadHistoryDemo.urlParamsTitle}</Typography.Text>
          <Table
            size="small"
            bordered
            pagination={false}
            rowKey="key"
            dataSource={urlParamRows}
            columns={[
              {
                title: messages.pages.userInfoDemo.parameterLabel,
                dataIndex: 'key',
                key: 'key',
                render: (value: string) => (
                  <Space size={6}>
                    <Typography.Text copyable={{ text: value }}>{value}</Typography.Text>
                    <Tag color={requiredUrlParams.has(value) ? 'error' : 'default'}>
                      {requiredUrlParams.has(value)
                        ? messages.pages.userInfoDemo.requiredLabel
                        : messages.pages.userInfoDemo.optionalLabel}
                    </Tag>
                  </Space>
                ),
              },
              {
                title: messages.pages.userInfoDemo.currentValueLabel,
                dataIndex: 'value',
                key: 'value',
                render: (value: string) => (
                  <Typography.Paragraph
                    copyable={value.trim() !== '' && value !== '-' ? { text: value } : false}
                    style={{ marginBottom: 0, wordBreak: 'break-all' }}
                  >
                    {value}
                  </Typography.Paragraph>
                ),
              },
              {
                title: messages.pages.userInfoDemo.purposeLabel,
                dataIndex: 'purpose',
                key: 'purpose',
              },
            ]}
          />

          
        </Space>
      </Card>

      <Card title={embedCodeCopy.title}>
        <Space orientation="vertical" size="middle" style={{ width: '100%' }}>
          <Typography.Paragraph type="secondary" style={{ marginBottom: 0 }}>
            {embedCodeCopy.description}
          </Typography.Paragraph>
          <Typography.Paragraph
            copyable={{ text: currentEmbedCodeExample }}
            style={{ ...codeBlockStyle, marginBottom: 0 }}
          >
            {currentEmbedCodeExample}
          </Typography.Paragraph>
        </Space>
      </Card>

      <Card title={threadHistoryMessages.apiGuide.title}>
        <Space orientation="vertical" size="middle" style={{ width: '100%' }}>
          {isAnonymousMode && (
            <Alert
              type="warning"
              showIcon
              title={threadApiGuide.anonymousHint}
            />
          )}

          <Typography.Text strong>{threadHistoryMessages.apiGuide.endpointLabel}</Typography.Text>
          <pre style={{ margin: 0, whiteSpace: 'pre-wrap', wordBreak: 'break-all' }}>{threadApiGuide.endpoint}</pre>

          <Typography.Text strong>{threadHistoryMessages.apiGuide.fullUrlPage1Label}</Typography.Text>
          <pre style={{ margin: 0, whiteSpace: 'pre-wrap', wordBreak: 'break-all' }}>{threadApiGuide.fullUrlPage1}</pre>

          <Typography.Text strong>{threadHistoryMessages.apiGuide.fullUrlPage2Label}</Typography.Text>
          <pre style={{ margin: 0, whiteSpace: 'pre-wrap', wordBreak: 'break-all' }}>{threadApiGuide.fullUrlPage2}</pre>

          <Typography.Text strong>{threadHistoryMessages.apiGuide.queryParamsTitle}</Typography.Text>
          <ul style={{ margin: 0, paddingLeft: 20, lineHeight: 1.8 }}>
            {threadApiGuide.queryParams.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>

          <Typography.Text strong>{threadHistoryMessages.apiGuide.pagingMappingTitle}</Typography.Text>
          <ul style={{ margin: 0, paddingLeft: 20, lineHeight: 1.8 }}>
            {threadApiGuide.pagingMapping.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>

          <Typography.Text strong>{threadHistoryMessages.apiGuide.curlExampleTitle}</Typography.Text>
          <pre style={{ margin: 0, whiteSpace: 'pre-wrap', wordBreak: 'break-all' }}>{threadApiGuide.curlExample}</pre>

          <Typography.Text strong>{threadHistoryMessages.apiGuide.fetchExampleTitle}</Typography.Text>
          <pre style={{ margin: 0, whiteSpace: 'pre-wrap', wordBreak: 'break-all' }}>{threadApiGuide.fetchExample}</pre>
        </Space>
      </Card>

      <Card title={threadHistoryMessages.responseGuide.title}>
        <Space orientation="vertical" size="middle" style={{ width: '100%' }}>
          <Typography.Text strong>{threadHistoryMessages.responseGuide.topLevelTitle}</Typography.Text>
          <ul style={{ margin: 0, paddingLeft: 20, lineHeight: 1.8 }}>
            {responseTopLevelFields.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>

          <Typography.Text strong>{threadHistoryMessages.responseGuide.dataFieldsTitle}</Typography.Text>
          <ul style={{ margin: 0, paddingLeft: 20, lineHeight: 1.8 }}>
            {responseDataFields.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>

          <Typography.Text strong>{threadHistoryMessages.responseGuide.threadItemFieldsTitle}</Typography.Text>
          <ul style={{ margin: 0, paddingLeft: 20, lineHeight: 1.8 }}>
            {threadItemFields.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>
        </Space>
      </Card>

      <BytedeskReact {...config} />

      <FloatButton.BackTop style={{ marginRight: 200, marginBottom: -30 }}/>
    </PageContainer>
  );
};

export default ThreadHistoryDemo;
